name: strike
description: A pure Dart SDK wrapper for the Strike APIs. Strike uses Bitcoin technology to offer instant payments globally, with no added fees. Use Strike to pay your friends, buy goods and services online, make micropayments, tip content creators, as well as buy and sell bitcoin.
version: 0.0.4
repository: https://github.com/jtmuller5/strike

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  json_serializable: ^6.1.6
  url_launcher: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter: